/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as VendorImport } from './routes/vendor'
import { Route as RegisterImport } from './routes/register'
import { Route as IndexImport } from './routes/index'
import { Route as DashboardVendorVendorIdImport } from './routes/dashboard/vendor/$vendorId'

// Create/Update Routes

const VendorRoute = VendorImport.update({
  path: '/vendor',
  getParentRoute: () => rootRoute,
} as any)

const RegisterRoute = RegisterImport.update({
  path: '/register',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const DashboardVendorVendorIdRoute = DashboardVendorVendorIdImport.update({
  path: '/dashboard/vendor/$vendorId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterImport
      parentRoute: typeof rootRoute
    }
    '/vendor': {
      id: '/vendor'
      path: '/vendor'
      fullPath: '/vendor'
      preLoaderRoute: typeof VendorImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/vendor/$vendorId': {
      id: '/dashboard/vendor/$vendorId'
      path: '/dashboard/vendor/$vendorId'
      fullPath: '/dashboard/vendor/$vendorId'
      preLoaderRoute: typeof DashboardVendorVendorIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/register': typeof RegisterRoute
  '/vendor': typeof VendorRoute
  '/dashboard/vendor/$vendorId': typeof DashboardVendorVendorIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/register': typeof RegisterRoute
  '/vendor': typeof VendorRoute
  '/dashboard/vendor/$vendorId': typeof DashboardVendorVendorIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/register': typeof RegisterRoute
  '/vendor': typeof VendorRoute
  '/dashboard/vendor/$vendorId': typeof DashboardVendorVendorIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/register' | '/vendor' | '/dashboard/vendor/$vendorId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/register' | '/vendor' | '/dashboard/vendor/$vendorId'
  id: '__root__' | '/' | '/register' | '/vendor' | '/dashboard/vendor/$vendorId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RegisterRoute: typeof RegisterRoute
  VendorRoute: typeof VendorRoute
  DashboardVendorVendorIdRoute: typeof DashboardVendorVendorIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RegisterRoute: RegisterRoute,
  VendorRoute: VendorRoute,
  DashboardVendorVendorIdRoute: DashboardVendorVendorIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/register",
        "/vendor",
        "/dashboard/vendor/$vendorId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/register": {
      "filePath": "register.tsx"
    },
    "/vendor": {
      "filePath": "vendor.tsx"
    },
    "/dashboard/vendor/$vendorId": {
      "filePath": "dashboard/vendor/$vendorId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
